volumes:
  db-store:

services:
  web:
    image: nginx:1.21.6-alpine
    ports:
      - "34251:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  app:
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
    ports:
      - "2435:3306"
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_bin"]
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - db-store:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1
    platform: linux/arm64 
    ports:
      - "8080:80"               # http://localhost:8080 で開く
    environment:
      PMA_HOST: db              
      PMA_USER: user            
      PMA_PASSWORD: secret
    depends_on:
      - db      